---
title: "Pearson Correlation Coef"
author: "Jerry Duran"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
# Data from GCTA and SOLAR programs
gcta_narrow_sense <- c(0.56, 0.46, 0.49, 0.56, 0.36, 0.34, 0.36, 0.26, 0.56, 0.35)
solar_narrow_sense <- c(0.51, 0.5, 0.36, 0.51, 0.32, 0.3, 0.36, 0.29, 0.37, 0.29)

# Calculating the Pearson Correlation Coefficient
correlation_coefficient <- cor(gcta_narrow_sense, solar_narrow_sense)
print(correlation_coefficient)

```

```{r}
library(dplyr)
library(ggplot2)
# Your data
data <- data.frame(
  Frequency = factor(c(250, 500, 1000, 2000, 3000, 4000, 6000, 8000, "Puretone Average", "High Frequency Average")),
  GCTA = c(0.56, 0.46, 0.49, 0.56, 0.36, 0.34, 0.36, 0.26, 0.56, 0.35),
  SOLAR = c(0.51, 0.5, 0.36, 0.51, 0.32, 0.3, 0.36, 0.29, 0.37, 0.29)
)

# Create a new column for color grouping
data$ColorGroup <- ifelse(data$Frequency %in% c(250, 2000), as.character(data$Frequency), "Other")

# Modify Frequency labels
data$Frequency <- factor(relevel(recode(as.factor(data$Frequency),
                                        `Puretone Average` = "PTA",
                                        `High Frequency Average` = "HFA"),
                                        ref = "250"))

# Scatter plot with labels
gcta_solar_correlation <- ggplot(data, aes(x = GCTA, y = SOLAR, label = Frequency, color = ColorGroup)) +
  geom_point(size = 3) +  # Increased point size for all except 250 Hz and 2000 Hz
  geom_point(data = subset(data, Frequency == 250), size = 4) +  # Larger point size for 250 Hz
  geom_point(data = subset(data, Frequency == 2000), size = 3) +  # Slightly smaller point size for 2000 Hz
  scale_color_manual(values = c("250" = "red", "2000" = "blue", "Other" = "black")) +  # Set colors manually
  geom_text(vjust = 1.5, hjust = 0.5, size = 4,    # Increased text size and adjusted position
            nudge_x = c(0, 0, 0, 0.02, 0, 0, 0, 0, 0, 0),
            nudge_y = c(0, 0, 0, 0.02, 0, 0, 0, 0, 0, 0)) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +  # Changed regression line color to black
  labs(x = "GCTA heritability estimates",
       y = "SOLAR heritability estimates",
       title = "Correlation of heritability estimates by frequency",
       color = "Pearson correlation coefficent=0.78\nPTA = Puretone average\nHFA = High frequency average\n\nFrequency labels in Hz",  # Updated legend title
       ) +  # Added correlation as caption
  theme_classic() +
  theme(plot.title = element_text(size = 22, face = "bold", hjust = 0.5, margin = margin(t = 10)),
        legend.position = "left",  # Adjusted legend position to bottom left corner
        legend.justification = c(0, 0),  # Justification sets the point of alignment for the legend
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face ="bold", margin = margin(r = 15)),
        axis.text.y = element_text(size = 12, face = "bold", margin = margin(t = 0, r = 0, b = 0, l = 0)),
        axis.ticks.x = element_blank(),
        panel.spacing.x = unit(1, "cm"),
        panel.spacing.y = unit(1, "cm"),
        axis.text.x = element_text(size = 12, face = "bold", hjust = 1, margin = margin(t = 0, r = 0, b = 0, l = 0)),
        panel.grid.major = element_line(color = "lightgrey", size = 0.1),  # Adding major grid lines
        panel.grid.minor = element_line(color = "lightgrey", size = 0.05),  # Adding minor grid lines
        plot.caption = element_text(hjust = 0, size = 12))  # Adjusted caption position and size

# Print the plot
print(gcta_solar_correlation)

# Save the plot with the specified name
ggsave("GCTA_SOLAR.png", plot = gcta_solar_correlation, width = 12, height = 8, dpi = 600)



```

